# Generated by Django 2.2.3 on 2019-07-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimpleModel',
            new_name='DbModel',
        ),
    ]
